// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnQ3lAbzkxvdaBSB4yHvMave2c5irhc5s',
    appId: '1:560198478988:web:892532a443dfcdad681fa9',
    messagingSenderId: '560198478988',
    projectId: 'emotenangis-9a3c2',
    authDomain: 'emotenangis-9a3c2.firebaseapp.com',
    storageBucket: 'emotenangis-9a3c2.firebasestorage.app',
    measurementId: 'G-VKCH8VZNBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbztM_ZFvz8xoJ9wb_wVaEx05zcqb-Hcw',
    appId: '1:560198478988:android:9f4b197ac5b714dd681fa9',
    messagingSenderId: '560198478988',
    projectId: 'emotenangis-9a3c2',
    storageBucket: 'emotenangis-9a3c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_rtQN-hawYXtIvTUnphJlHURsAUoLA8E',
    appId: '1:560198478988:ios:49d8d73177d46ef3681fa9',
    messagingSenderId: '560198478988',
    projectId: 'emotenangis-9a3c2',
    storageBucket: 'emotenangis-9a3c2.firebasestorage.app',
    iosBundleId: 'com.example.emoteNangis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_rtQN-hawYXtIvTUnphJlHURsAUoLA8E',
    appId: '1:560198478988:ios:49d8d73177d46ef3681fa9',
    messagingSenderId: '560198478988',
    projectId: 'emotenangis-9a3c2',
    storageBucket: 'emotenangis-9a3c2.firebasestorage.app',
    iosBundleId: 'com.example.emoteNangis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnQ3lAbzkxvdaBSB4yHvMave2c5irhc5s',
    appId: '1:560198478988:web:6b1fa18636649102681fa9',
    messagingSenderId: '560198478988',
    projectId: 'emotenangis-9a3c2',
    authDomain: 'emotenangis-9a3c2.firebaseapp.com',
    storageBucket: 'emotenangis-9a3c2.firebasestorage.app',
    measurementId: 'G-SPECTMCR0X',
  );
}
